In [6]:
import numpy as np

In [7]:
rs_arr = np.load("NA12878.chrom20.ILLUMINA.bwa.CEU.low_coverage.20121211.bam.npy")
py_arr = np.load("NA12878.chrom20.ILLUMINA.bwa.CEU.low_coverage.20121211.bam.py.npy")

In [8]:
d = np.where(rs_arr != py_arr)
display(d[0].shape)
d

(88,)

(array([ 17,  17,  49,  49,  49,  49,  57,  57,  89,  89,  89,  89, 129,
        129, 129, 129, 161, 161, 169, 169, 169, 169, 169, 169, 169, 169,
        169, 169, 169, 169, 169, 169, 193, 193, 209, 209, 209, 209, 209,
        209, 233, 233, 241, 241, 249, 249, 249, 249, 249, 249, 257, 257,
        265, 265, 273, 273, 281, 281, 289, 289, 289, 289, 289, 289, 289,
        289, 297, 297, 305, 305, 313, 313, 313, 313, 321, 321, 329, 329,
        329, 329, 329, 329, 329, 329, 337, 337, 345, 345]),
 array([62, 63, 42, 43, 62, 63, 62, 63, 42, 43, 47, 48, 42, 43, 47, 48, 62,
        63, 30, 31, 34, 35, 36, 37, 42, 43, 44, 47, 49, 50, 59, 60, 62, 63,
        42, 43, 47, 48, 62, 63, 62, 63, 62, 63, 42, 43, 47, 48, 62, 63, 62,
        63, 62, 63, 62, 63, 62, 63, 42, 43, 47, 48, 62, 63, 72, 73, 62, 63,
        62, 63, 12, 13, 62, 63, 62, 63, 42, 43, 47, 48, 62, 63, 72, 73, 62,
        63, 62, 63]))

In [5]:
rs_arr[d] - py_arr[d]

array([   1.,   -1.,    2.,   -2.,   -1.,    1.,   -3.,    3.,    1.,
         -1.,   -1.,    1.,    2.,   -2.,    1.,   -1.,    2.,   -2.,
          1.,   -1.,   -3.,    3.,    3.,   -3.,   -1.,    3.,   -2.,
          1.,   -2.,    1.,   -2.,    5.,   -3.,    2.,   -2.,   -1.,
          1.,    1.,   -1.,    1.,   -1.,    2.,   -2.,   -4.,    4.,
          4.,   -4.,   -2.,    2.,    1.,   -1.,   10.,  -10.,  -21.,
         21.,   13.,  -13.,   -3.,    3.,    1.,   -1.,   51.,  -51.,
        -83.,   83.,   50.,  -50.,  -18.,   18.,    2.,   -2.,   93.,
        -93., -174.,  174.,  111., -111.,  -30.,   30.])

In [10]:
rs_arr[d], py_arr[d]

(array([  1,   0,   2,   0,   0,   1,   1,   3,   2,   5,   1,   2,   3,
          2,   1,   0,   2,   1,   2,   0,   2,   7,   8,   0,   2,   5,
          0,   2,   1,   3,   1,   8,   0,   3,   0,   0,   1,   1,   0,
          1,   0,   9,   3,   8,  10,  13,   7,   2,   3,   1,   1,  28,
         24,  35,  41,  42,  19,   8,  11,   2,   3, 204, 144, 220, 312,
        232, 133,  72,  64,   8,  12, 359, 334, 559, 718, 491, 262, 104,
        135], dtype=uint64),
 array([  0.,   1.,   0.,   2.,   1.,   0.,   4.,   0.,   1.,   6.,   2.,
          1.,   1.,   4.,   0.,   1.,   0.,   3.,   1.,   1.,   5.,   4.,
          5.,   3.,   3.,   2.,   2.,   1.,   3.,   2.,   3.,   3.,   3.,
          1.,   2.,   1.,   0.,   0.,   1.,   0.,   1.,   7.,   5.,  12.,
          6.,   9.,  11.,   4.,   1.,   0.,   2.,  18.,  34.,  56.,  20.,
         29.,  32.,  11.,   8.,   1.,   4., 153., 195., 303., 229., 182.,
        183.,  90.,  46.,   6.,  14., 266., 427., 733., 544., 380., 373.,
        134., 1

In [20]:
88 / (350*101) * 100

0.24893917963224893