In [1]:
import numpy as np

In [7]:
rs_arr = np.load("NA12878.chrom20.ILLUMINA.bwa.CEU.low_coverage.20121211.bam.npy")
py_arr = np.load("NA12878.chrom20.ILLUMINA.bwa.CEU.low_coverage.20121211.bam.py.npy")

In [8]:
d = np.where(rs_arr != py_arr)
display(d[0].shape)
d

(79,)

(array([  9,   9,  49,  49,  49,  49,  89,  89, 129, 129, 129, 129, 129,
        129, 169, 169, 169, 169, 169, 169, 169, 169, 169, 169, 169, 169,
        169, 169, 169, 169, 169, 169, 169, 169, 169, 169, 169, 169, 169,
        169, 169, 209, 209, 209, 209, 209, 209, 209, 209, 249, 249, 249,
        249, 249, 249, 249, 249, 249, 249, 289, 289, 289, 289, 289, 289,
        289, 289, 289, 289, 329, 329, 329, 329, 329, 329, 329, 329, 329,
        329]),
 array([22, 23, 32, 33, 57, 58, 47, 48, 32, 33, 47, 48, 52, 53, 22, 23, 26,
        27, 32, 33, 35, 36, 40, 41, 43, 44, 45, 46, 47, 48, 49, 50, 51, 54,
        55, 59, 60, 66, 67, 68, 69, 32, 33, 47, 48, 52, 53, 57, 58, 22, 23,
        32, 33, 47, 48, 52, 53, 57, 58, 22, 23, 32, 33, 47, 48, 52, 53, 57,
        58, 22, 23, 32, 33, 47, 48, 52, 53, 57, 58]))

In [9]:
rs_arr[d], py_arr[d]

(array([  1,   0,   2,   0,   0,   1,   1,   3,   2,   5,   1,   2,   3,
          2,   1,   0,   2,   1,   2,   0,   2,   7,   8,   0,   2,   5,
          0,   2,   1,   3,   1,   8,   0,   3,   0,   0,   1,   1,   0,
          1,   0,   9,   3,   8,  10,  13,   7,   2,   3,   1,   1,  28,
         24,  35,  41,  42,  19,   8,  11,   2,   3, 204, 144, 220, 312,
        232, 133,  72,  64,   8,  12, 359, 334, 559, 718, 491, 262, 104,
        135], dtype=uint64),
 array([  0.,   1.,   0.,   2.,   1.,   0.,   4.,   0.,   1.,   6.,   2.,
          1.,   1.,   4.,   0.,   1.,   0.,   3.,   1.,   1.,   5.,   4.,
          5.,   3.,   3.,   2.,   2.,   1.,   3.,   2.,   3.,   3.,   3.,
          1.,   2.,   1.,   0.,   0.,   1.,   0.,   1.,   7.,   5.,  12.,
          6.,   9.,  11.,   4.,   1.,   0.,   2.,  18.,  34.,  56.,  20.,
         29.,  32.,  11.,   8.,   1.,   4., 153., 195., 303., 229., 182.,
        183.,  90.,  46.,   6.,  14., 266., 427., 733., 544., 380., 373.,
        134., 1

In [10]:
rs_arr[d], py_arr[d]

(array([  1,   0,   2,   0,   0,   1,   1,   3,   2,   5,   1,   2,   3,
          2,   1,   0,   2,   1,   2,   0,   2,   7,   8,   0,   2,   5,
          0,   2,   1,   3,   1,   8,   0,   3,   0,   0,   1,   1,   0,
          1,   0,   9,   3,   8,  10,  13,   7,   2,   3,   1,   1,  28,
         24,  35,  41,  42,  19,   8,  11,   2,   3, 204, 144, 220, 312,
        232, 133,  72,  64,   8,  12, 359, 334, 559, 718, 491, 262, 104,
        135], dtype=uint64),
 array([  0.,   1.,   0.,   2.,   1.,   0.,   4.,   0.,   1.,   6.,   2.,
          1.,   1.,   4.,   0.,   1.,   0.,   3.,   1.,   1.,   5.,   4.,
          5.,   3.,   3.,   2.,   2.,   1.,   3.,   2.,   3.,   3.,   3.,
          1.,   2.,   1.,   0.,   0.,   1.,   0.,   1.,   7.,   5.,  12.,
          6.,   9.,  11.,   4.,   1.,   0.,   2.,  18.,  34.,  56.,  20.,
         29.,  32.,  11.,   8.,   1.,   4., 153., 195., 303., 229., 182.,
        183.,  90.,  46.,   6.,  14., 266., 427., 733., 544., 380., 373.,
        134., 1

In [20]:
88 / (350*101) * 100

0.24893917963224893